plugins {
    id 'maven-publish'
}

group = 'com.github.singbox-android'
version = '1.12.24'

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = 'libbox'
            artifact 'libbox.aar'
            artifact('libbox-sources.jar') {
                classifier = 'sources'
            }
        }
    }
}